import { useMobileConnectionActions } from "./useMobileConnectionActions";
import { useMobilePushNotifications } from "./useMobilePushNotifications";
import { useMobilePurchaseActions } from "./useMobilePurchaseActions";
import { useMobileAccountSessionActions } from "./useMobileAccountSessionActions";
import { useMobileDiagnosticsActions } from "./useMobileDiagnosticsActions";
import { useMobilePairingAndDeepLinks } from "./useMobilePairingAndDeepLinks";

type UseMobileSettingsActionsControllerInput =
  Parameters<typeof useMobileConnectionActions>[0] &
  Parameters<typeof useMobilePushNotifications>[0] &
  Parameters<typeof useMobilePurchaseActions>[0] &
  Parameters<typeof useMobileAccountSessionActions>[0] &
  Parameters<typeof useMobileDiagnosticsActions>[0] &
  Omit<Parameters<typeof useMobilePairingAndDeepLinks>[0], "handleServerURLChange">;

export function useMobileSettingsActionsController({
  activeClerkSessionID,
  activeConnectionID,
  bestEffortUnregisterSavedAccounts,
  clerkSessionToken,
  clerkSignedIn,
  connectionStatus,
  currentAccountProfile,
  currentAuthToken,
  deviceID,
  didPrimeNotifications,
  error,
  hasRequestAuth,
  interruptRealtime,
  isHostedAccount,
  lastClerkPushRegistrationKey,
  load,
  loadRef,
  notificationTargetID,
  notificationsEnabled,
  notificationStatus,
  onForgetClerkSession,
  onRuntimeAuthConfig,
  pairingCode,
  personalBillingStatus,
  purchaseAccountReady,
  purchaseInFlightRef,
  pushStatus,
  refreshPersonalBilling,
  refreshStoreEntitlements,
  runtimeAuthProvider,
  savedAccounts,
  seenRequestIDs,
  screen,
  sdk,
  selectedWorkspace,
  selectedWorkspaceID,
  serverURL,
  settingsLoaded,
  setAccountPending,
  setAvailability,
  setConnectionStatus,
  setConnectionTokens,
  setCurrentAccountProfile,
  setDebugPaywallVisible,
  setDeviceID,
  setDiagnosticsEnabled,
  setDiagnosticsEventCount,
  setDiagnosticsLastSentAt,
  setError,
  setHistory,
  setLoadedSessionServerURL,
  setLocalStoreHostedSubscriptionActive,
  setLocalStoreLifetimeUnlocked,
  setLocalStoreTrialPurchased,
  setLocalStoreTrialStartedAt,
  setLoading,
  setNotificationStatus,
  setNotificationsEnabled,
  setNotificationTargetID,
  setNotificationTargetRequestID,
  setNotificationTargetSessionID,
  setNotificationTargetStatusUpdateID,
  setPairingCode,
  setPaywallConfig,
  setPaywallDismissedKey,
  setPersonalBillingStatus,
  setPurchaseInFlightProductKey,
  setPushStatus,
  setRequests,
  setRuntimeAuthConfig,
  setSavedAccounts,
  setSelectedID,
  setSelectedSourceID,
  setSelectedWorkspaceID,
  setServerURL,
  setScreen,
  setStatusUpdates,
  setStoreEntitlementsSettled,
  setStoreProducts,
  setToken,
  setWorkspaces,
  token,
}: UseMobileSettingsActionsControllerInput) {
  const { checkConnection, updateAvailability } = useMobileConnectionActions({
    interruptRealtime,
    load,
    sdk,
    setAvailability,
    setConnectionStatus,
  });

  const {
    requestNotifications,
    toggleNotifications,
    sendTestNotification,
    registerPushToken,
  } = useMobilePushNotifications({
    activeConnectionID,
    currentAccountProfile,
    currentAuthToken,
    deviceID,
    isHostedAccount,
    lastClerkPushRegistrationKey,
    notificationsEnabled,
    notificationStatus,
    personalBillingStatus,
    pushStatus,
    runtimeAuthProvider,
    savedAccounts,
    sdk,
    selectedWorkspace,
    selectedWorkspaceID,
    serverURL,
    settingsLoaded,
    setDeviceID,
    setDiagnosticsEventCount,
    setNotificationStatus,
    setNotificationsEnabled,
    setPushStatus,
    setSavedAccounts,
    token,
  });

  const {
    startTrial,
    purchaseLifetimeUnlock,
    restorePurchases,
    linkPurchasesToHostedAccount,
    subscribeHostedPersonal,
    manageSubscription,
  } = useMobilePurchaseActions({
    currentAccountProfile,
    personalBillingStatus,
    purchaseAccountReady,
    purchaseInFlightRef,
    refreshPersonalBilling,
    refreshStoreEntitlements,
    runtimeAuthProvider,
    sdk,
    setPurchaseInFlightProductKey,
  });

  const {
    bestEffortUnregisterDevice,
    clearHostedLoginSession,
    clearStoredSessionForServer,
    deleteAccount,
    forgetDevice,
    handleServerURLChange,
    resetLocalTestState,
    selectWorkspace,
    signOutFromSettings,
    useHostedSignIn,
  } = useMobileAccountSessionActions({
    activeClerkSessionID,
    bestEffortUnregisterSavedAccounts,
    clerkSessionToken,
    clerkSignedIn,
    currentAccountProfile,
    currentAuthToken,
    deviceID,
    onForgetClerkSession,
    onRuntimeAuthConfig,
    runtimeAuthProvider,
    savedAccounts,
    sdk,
    selectedWorkspaceID,
    serverURL,
    setAccountPending,
    setConnectionStatus,
    setConnectionTokens,
    setCurrentAccountProfile,
    setDebugPaywallVisible,
    setDeviceID,
    setDiagnosticsEnabled,
    setDiagnosticsEventCount,
    setError,
    setHistory,
    setLoadedSessionServerURL,
    setLocalStoreHostedSubscriptionActive,
    setLocalStoreLifetimeUnlocked,
    setLocalStoreTrialPurchased,
    setLocalStoreTrialStartedAt,
    setLoading,
    setNotificationTargetID,
    setNotificationsEnabled,
    setPaywallConfig,
    setPaywallDismissedKey,
    setPersonalBillingStatus,
    setPushStatus,
    setRequests,
    setSavedAccounts,
    setSelectedID,
    setSelectedSourceID,
    setSelectedWorkspaceID,
    setServerURL,
    setStatusUpdates,
    setStoreEntitlementsSettled,
    setStoreProducts,
    setToken,
    setWorkspaces,
    token,
  });

  const { toggleDiagnostics, sendDiagnostics } = useMobileDiagnosticsActions({
    connectionStatus,
    error,
    hasRequestAuth,
    notificationStatus,
    notificationsEnabled,
    pushStatus,
    runtimeAuthProvider,
    savedAccounts,
    screen,
    sdk,
    serverURL,
    setDiagnosticsEnabled,
    setDiagnosticsEventCount,
    setDiagnosticsLastSentAt,
  });

  const { handlePairingScan, openScanner, pairDevice, scannerLocked } = useMobilePairingAndDeepLinks({
    currentAuthToken,
    didPrimeNotifications,
    handleServerURLChange,
    interruptRealtime,
    load,
    loadRef,
    notificationTargetID,
    notificationsEnabled,
    onRuntimeAuthConfig,
    pairingCode,
    pushStatus,
    seenRequestIDs,
    serverURL,
    setConnectionStatus,
    setDeviceID,
    setNotificationTargetID,
    setNotificationTargetRequestID,
    setNotificationTargetSessionID,
    setNotificationTargetStatusUpdateID,
    setPairingCode,
    setPushStatus,
    setRequests,
    setRuntimeAuthConfig,
    setScreen,
    setSelectedID,
    setSelectedWorkspaceID,
    setServerURL,
    setToken,
    setWorkspaces,
  });

  return {
    checkConnection,
    updateAvailability,
    requestNotifications,
    toggleNotifications,
    sendTestNotification,
    registerPushToken,
    startTrial,
    purchaseLifetimeUnlock,
    restorePurchases,
    linkPurchasesToHostedAccount,
    subscribeHostedPersonal,
    manageSubscription,
    bestEffortUnregisterDevice,
    clearHostedLoginSession,
    clearStoredSessionForServer,
    deleteAccount,
    forgetDevice,
    handleServerURLChange,
    resetLocalTestState,
    selectWorkspace,
    signOutFromSettings,
    useHostedSignIn,
    toggleDiagnostics,
    sendDiagnostics,
    handlePairingScan,
    openScanner,
    pairDevice,
    scannerLocked,
  };
}
