packages:
  - "apps/*"
  - "packages/*"
  - "sites/*"

onlyBuiltDependencies:
  - "@clerk/shared"
  - "better-sqlite3"
  - "esbuild"

ignoredBuiltDependencies:
  - "browser-tabs-lock"
  - "bufferutil"
  - "core-js"
  - "utf-8-validate"

patchedDependencies:
  "@clerk/expo@3.2.10": patches/@clerk__expo@3.2.10.patch
