packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@clerk/shared"
  - "better-sqlite3"
  - "esbuild"

ignoredBuiltDependencies:
  - "browser-tabs-lock"
  - "bufferutil"
  - "core-js"
  - "utf-8-validate"
