export interface PostgresMigration {
  version: string;
  sql: string;
}

export const POSTGRES_MIGRATIONS: PostgresMigration[] = [
  {
    version: '0001_core',
    sql: `
CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL DEFAULT '',
  email_verified BOOLEAN NOT NULL DEFAULT false,
  name TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_idx ON users(email) WHERE email <> '';

CREATE TABLE IF NOT EXISTS auth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  issuer TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id),
  email TEXT NOT NULL DEFAULT '',
  email_verified BOOLEAN NOT NULL DEFAULT false,
  name TEXT NOT NULL DEFAULT '',
  auth_method TEXT,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(provider, issuer, subject)
);

CREATE INDEX IF NOT EXISTS auth_identities_user_idx ON auth_identities(user_id);

CREATE TABLE IF NOT EXISTS organizations (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS organization_memberships (
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  approved_by_user_id TEXT,
  approved_at TEXT,
  rejected_by_user_id TEXT,
  rejected_at TEXT,
  invite_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (organization_id, user_id)
);

CREATE INDEX IF NOT EXISTS organization_memberships_status_idx ON organization_memberships(organization_id, status);

CREATE TABLE IF NOT EXISTS projects (
  project_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  archived_at TEXT,
  UNIQUE(organization_id, slug)
);

CREATE INDEX IF NOT EXISTS projects_org_idx ON projects(organization_id, archived_at, name);

CREATE TABLE IF NOT EXISTS teams (
  team_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  archived_at TEXT,
  UNIQUE(organization_id, slug)
);

CREATE INDEX IF NOT EXISTS teams_org_idx ON teams(organization_id, archived_at, name);

CREATE TABLE IF NOT EXISTS team_memberships (
  team_id TEXT NOT NULL REFERENCES teams(team_id),
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  role TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (team_id, user_id)
);

CREATE INDEX IF NOT EXISTS team_memberships_user_idx ON team_memberships(organization_id, user_id);

CREATE TABLE IF NOT EXISTS organization_invites (
  invite_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  label TEXT,
  role TEXT NOT NULL,
  approval_required BOOLEAN NOT NULL DEFAULT true,
  token_hash TEXT NOT NULL UNIQUE,
  email TEXT,
  domain TEXT,
  expires_at TEXT,
  max_uses INTEGER,
  used_count INTEGER NOT NULL DEFAULT 0,
  email_last_status TEXT,
  email_last_sent_at TEXT,
  email_last_error TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS organization_invites_org_idx ON organization_invites(organization_id, revoked_at, created_at);
CREATE INDEX IF NOT EXISTS organization_invites_token_idx ON organization_invites(token_hash);

CREATE TABLE IF NOT EXISTS organization_invite_teams (
  invite_id TEXT NOT NULL REFERENCES organization_invites(invite_id),
  team_id TEXT NOT NULL REFERENCES teams(team_id),
  PRIMARY KEY (invite_id, team_id)
);

CREATE INDEX IF NOT EXISTS organization_invite_teams_team_idx ON organization_invite_teams(team_id);

CREATE TABLE IF NOT EXISTS organization_invite_acceptances (
  request_id TEXT PRIMARY KEY,
  invite_id TEXT NOT NULL REFERENCES organization_invites(invite_id),
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  requested_role TEXT NOT NULL,
  requested_team_ids_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL,
  accepted_at TEXT NOT NULL,
  decided_by_user_id TEXT,
  decided_at TEXT,
  UNIQUE(invite_id, user_id)
);

CREATE INDEX IF NOT EXISTS organization_invite_acceptances_org_status_idx ON organization_invite_acceptances(organization_id, status, accepted_at);
CREATE INDEX IF NOT EXISTS organization_invite_acceptances_user_idx ON organization_invite_acceptances(user_id);

CREATE TABLE IF NOT EXISTS policies (
  policy_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  name TEXT NOT NULL,
  description TEXT,
  project_id TEXT REFERENCES projects(project_id),
  team_id TEXT REFERENCES teams(team_id),
  required_approvals INTEGER NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  archived_at TEXT
);

CREATE INDEX IF NOT EXISTS policies_org_idx ON policies(organization_id, enabled, archived_at, name);

CREATE TABLE IF NOT EXISTS agent_tokens (
  agent_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  owner_user_id TEXT REFERENCES users(id),
  project_id TEXT REFERENCES projects(project_id),
  team_id TEXT REFERENCES teams(team_id),
  default_approval_policy TEXT REFERENCES policies(policy_id),
  name TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  scopes_json TEXT NOT NULL,
  last_request_at TEXT,
  created_at TEXT NOT NULL,
  revoked_at TEXT
);

CREATE INDEX IF NOT EXISTS agent_tokens_org_idx ON agent_tokens(organization_id);

CREATE TABLE IF NOT EXISTS approval_requests (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  user_id TEXT REFERENCES users(id),
  requester_name TEXT NOT NULL,
  requester_agent_id TEXT NOT NULL,
  requester_host TEXT,
  requester_working_directory TEXT,
  requester_project_name TEXT,
  requester_project_id TEXT,
  request_type TEXT NOT NULL DEFAULT 'approval',
  title TEXT NOT NULL,
  body TEXT,
  command TEXT,
  encrypted_payload_json TEXT,
  choices_json TEXT NOT NULL,
  questions_json TEXT NOT NULL DEFAULT '[]',
  default_choice TEXT,
  allow_freeform_reply BOOLEAN NOT NULL DEFAULT false,
  expires_at TEXT,
  risk TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  responded_at TEXT,
  response_json TEXT
);

CREATE INDEX IF NOT EXISTS approval_requests_org_status_idx ON approval_requests(organization_id, status, created_at);

CREATE TABLE IF NOT EXISTS approval_recipients (
  request_id TEXT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id),
  organization_id TEXT REFERENCES organizations(id),
  source TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  notified_at TEXT,
  seen_at TEXT,
  responded_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(request_id, user_id)
);

CREATE INDEX IF NOT EXISTS approval_recipients_user_idx ON approval_recipients(user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS approval_recipients_request_idx ON approval_recipients(request_id);

CREATE TABLE IF NOT EXISTS approval_votes (
  vote_id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
  policy_id TEXT REFERENCES policies(policy_id),
  step INTEGER NOT NULL DEFAULT 1,
  approver_user_id TEXT NOT NULL REFERENCES users(id),
  source TEXT NOT NULL,
  choice_id TEXT NOT NULL,
  message TEXT,
  answers_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(request_id, approver_user_id, step)
);

CREATE INDEX IF NOT EXISTS approval_votes_request_idx ON approval_votes(request_id, step, created_at);

CREATE TABLE IF NOT EXISTS approval_waiter_tokens (
  token_hash TEXT PRIMARY KEY,
  request_id TEXT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  agent_id TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  last_used_at TEXT
);

CREATE INDEX IF NOT EXISTS approval_waiter_tokens_request_idx ON approval_waiter_tokens(request_id, expires_at);
CREATE INDEX IF NOT EXISTS approval_waiter_tokens_expires_idx ON approval_waiter_tokens(expires_at);

CREATE TABLE IF NOT EXISTS event_tickets (
  ticket_hash TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  user_id TEXT,
  agent_id TEXT,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  last_used_at TEXT
);

CREATE INDEX IF NOT EXISTS event_tickets_expires_idx ON event_tickets(expires_at);

CREATE TABLE IF NOT EXISTS user_availability (
  user_id TEXT NOT NULL REFERENCES users(id),
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  state TEXT NOT NULL,
  last_seen_at TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(user_id, organization_id)
);

CREATE TABLE IF NOT EXISTS pairing_codes (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  used_at TEXT
);

CREATE INDEX IF NOT EXISTS pairing_codes_expires_idx ON pairing_codes(expires_at);

CREATE TABLE IF NOT EXISTS devices (
  device_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  platform TEXT,
  installation_id TEXT,
  expo_push_token TEXT,
  token_hash TEXT UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  unregistered_at TEXT
);

CREATE INDEX IF NOT EXISTS devices_user_idx ON devices(user_id, unregistered_at);
CREATE UNIQUE INDEX IF NOT EXISTS devices_user_installation_idx ON devices(user_id, installation_id) WHERE installation_id IS NOT NULL AND unregistered_at IS NULL;

CREATE TABLE IF NOT EXISTS audit_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS audit_events_org_event_idx ON audit_events(organization_id, event_id);

CREATE TABLE IF NOT EXISTS mobile_diagnostics (
  diagnostic_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  device_id TEXT,
  level TEXT NOT NULL,
  area TEXT NOT NULL,
  message TEXT NOT NULL,
  metadata_json TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS mobile_diagnostics_org_created_idx ON mobile_diagnostics(organization_id, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_status_updates (
  status_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  agent_id TEXT NOT NULL,
  agent_name TEXT NOT NULL,
  thread_id TEXT NOT NULL,
  message TEXT NOT NULL,
  state TEXT NOT NULL,
  next_step TEXT,
  host TEXT,
  working_directory TEXT,
  project_name TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS agent_status_updates_org_thread_created_idx ON agent_status_updates(organization_id, thread_id, created_at DESC);
CREATE INDEX IF NOT EXISTS agent_status_updates_org_created_idx ON agent_status_updates(organization_id, created_at DESC);
`
  },
  {
    version: '0002_approval_questions',
    sql: `
ALTER TABLE approval_requests ADD COLUMN IF NOT EXISTS questions_json TEXT NOT NULL DEFAULT '[]';
`
  },
  {
    version: '0003_personal_entitlements',
    sql: `
CREATE TABLE IF NOT EXISTS personal_entitlements (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  trial_started_at TEXT NOT NULL,
  app_unlocked_at TEXT,
  included_hosted_activated_at TEXT,
  hosted_subscription_ends_at TEXT,
  hosted_subscription_canceled_at TEXT,
  hosted_data_deleted_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`
  },
  {
    version: '0004_billing',
    sql: `
CREATE TABLE IF NOT EXISTS billing_products (
  id TEXT PRIMARY KEY,
  product_key TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL,
  entitlement_key TEXT NOT NULL,
  apple_product_id TEXT,
  google_product_id TEXT,
  google_base_plan_id TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_purchase_attempts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_key TEXT NOT NULL,
  product_group TEXT NOT NULL,
  platform TEXT NOT NULL,
  provider TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_user_id TEXT,
  idempotency_key TEXT NOT NULL UNIQUE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS billing_purchase_attempts_user_group_idx ON billing_purchase_attempts(user_id, product_group, status, expires_at);

CREATE TABLE IF NOT EXISTS billing_transactions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  environment TEXT NOT NULL,
  product_key TEXT NOT NULL,
  entitlement_key TEXT NOT NULL,
  platform TEXT NOT NULL,
  provider_transaction_id TEXT,
  provider_original_transaction_id TEXT,
  provider_purchase_token TEXT,
  status TEXT NOT NULL,
  purchased_at TEXT,
  expires_at TEXT,
  canceled_at TEXT,
  revoked_at TEXT,
  raw_event_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS billing_transactions_provider_transaction_idx ON billing_transactions(provider, provider_transaction_id) WHERE provider_transaction_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS billing_transactions_provider_original_product_idx ON billing_transactions(provider, provider_original_transaction_id, product_key) WHERE provider_original_transaction_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS billing_transactions_provider_purchase_token_idx ON billing_transactions(provider, provider_purchase_token) WHERE provider_purchase_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS billing_transactions_user_entitlement_status_idx ON billing_transactions(user_id, entitlement_key, status);
`
  }
];
