export const POSTGRES_SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL DEFAULT '',
  email_verified BOOLEAN NOT NULL DEFAULT false,
  name TEXT NOT NULL DEFAULT '',
  sign_in_method TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_idx ON users(lower(email)) WHERE email <> '';

CREATE TABLE IF NOT EXISTS auth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  issuer TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email TEXT NOT NULL DEFAULT '',
  email_verified BOOLEAN NOT NULL DEFAULT false,
  name TEXT NOT NULL DEFAULT '',
  auth_method TEXT,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(provider, issuer, subject)
);
CREATE INDEX IF NOT EXISTS auth_identities_user_idx ON auth_identities(user_id);

CREATE TABLE IF NOT EXISTS workspaces (
  workspace_id TEXT PRIMARY KEY,
  type TEXT NOT NULL CHECK(type IN ('personal', 'shared')),
  name TEXT NOT NULL,
  clerk_organization_id TEXT UNIQUE,
  responses_entitled_until TEXT,
  private_requests_required BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workspace_members (
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  member_kind TEXT NOT NULL DEFAULT 'internal',
  status TEXT NOT NULL DEFAULT 'active',
  clerk_membership_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(workspace_id, user_id)
);
CREATE INDEX IF NOT EXISTS workspace_members_user_idx ON workspace_members(user_id, status);
CREATE INDEX IF NOT EXISTS workspace_members_workspace_status_idx ON workspace_members(workspace_id, status);

CREATE TABLE IF NOT EXISTS routing_rules (
  routing_rule_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  required_response_mode TEXT NOT NULL DEFAULT 'any_one',
  required_response_count INTEGER NOT NULL DEFAULT 1,
  private_requests_required BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS routing_rules_workspace_idx ON routing_rules(workspace_id, name);

CREATE TABLE IF NOT EXISTS routing_rule_recipients (
  routing_rule_id TEXT NOT NULL REFERENCES routing_rules(routing_rule_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY(routing_rule_id, user_id)
);

CREATE TABLE IF NOT EXISTS agent_tokens (
  agent_token_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  creator_user_id TEXT REFERENCES users(id),
  routing_rule_id TEXT REFERENCES routing_rules(routing_rule_id) ON DELETE SET NULL,
  bound_recipient_user_id TEXT REFERENCES users(id),
  label TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  scopes_json TEXT NOT NULL DEFAULT '[]',
  last_activity_at TEXT,
  last_check_in_at TEXT,
  created_at TEXT NOT NULL,
  revoked_at TEXT
);
CREATE INDEX IF NOT EXISTS agent_tokens_workspace_idx ON agent_tokens(workspace_id, revoked_at, created_at);

CREATE TABLE IF NOT EXISTS requests (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  agent_token_id TEXT REFERENCES agent_tokens(agent_token_id) ON DELETE SET NULL,
  routing_rule_id TEXT REFERENCES routing_rules(routing_rule_id) ON DELETE SET NULL,
  session_id TEXT,
  session_metadata_json TEXT NOT NULL DEFAULT '{}',
  requester_json TEXT NOT NULL,
  request_type TEXT NOT NULL,
  delivery_kind TEXT NOT NULL DEFAULT 'routed_members',
  response_policy TEXT NOT NULL DEFAULT 'quorum',
  audience_channel_id TEXT,
  closes_at TEXT,
  tie_policy TEXT,
  aggregate_result_json TEXT,
  title TEXT NOT NULL,
  body TEXT,
  command TEXT,
  choices_json TEXT NOT NULL,
  questions_json TEXT NOT NULL DEFAULT '[]',
  default_choice TEXT,
  allow_freeform_reply BOOLEAN NOT NULL DEFAULT false,
  deadline TEXT,
  risk TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  content_mode TEXT NOT NULL DEFAULT 'plain',
  encrypted_payload_json TEXT,
  private_recipient_version TEXT,
  private_unavailable_recipients_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL,
  required_response_count INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  responded_at TEXT,
  response_json TEXT,
  final_choice_id TEXT,
  is_test BOOLEAN NOT NULL DEFAULT false,
  test_label TEXT
);
CREATE INDEX IF NOT EXISTS requests_workspace_status_idx ON requests(workspace_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS requests_pending_deadline_idx ON requests(deadline) WHERE status = 'pending' AND deadline IS NOT NULL;
CREATE INDEX IF NOT EXISTS requests_audience_finalize_idx ON requests(closes_at) WHERE status = 'pending' AND delivery_kind = 'audience_channel' AND closes_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS request_recipients (
  request_id TEXT NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  has_active_device BOOLEAN NOT NULL DEFAULT false,
  responded_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(request_id, user_id)
);
CREATE INDEX IF NOT EXISTS request_recipients_user_idx ON request_recipients(user_id, request_id);
CREATE INDEX IF NOT EXISTS request_recipients_pending_count_idx ON request_recipients(user_id, request_id, responded_at);

CREATE TABLE IF NOT EXISTS audience_channels (
  channel_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT,
  visibility TEXT NOT NULL DEFAULT 'invite_only',
  status TEXT NOT NULL DEFAULT 'active',
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(workspace_id, slug)
);
CREATE INDEX IF NOT EXISTS audience_channels_workspace_idx ON audience_channels(workspace_id, status, name);

CREATE TABLE IF NOT EXISTS audience_subscriptions (
  channel_id TEXT NOT NULL REFERENCES audience_channels(channel_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(channel_id, user_id)
);
CREATE INDEX IF NOT EXISTS audience_subscriptions_user_idx ON audience_subscriptions(user_id, status);

CREATE TABLE IF NOT EXISTS external_approvers (
  external_approver_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  external_subject TEXT,
  display_name TEXT,
  user_id TEXT REFERENCES users(id),
  routing_rule_id TEXT REFERENCES routing_rules(routing_rule_id) ON DELETE SET NULL,
  agent_token_id TEXT REFERENCES agent_tokens(agent_token_id) ON DELETE SET NULL,
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS external_approvers_workspace_subject_idx ON external_approvers(workspace_id, external_subject) WHERE external_subject IS NOT NULL;
CREATE INDEX IF NOT EXISTS external_approvers_workspace_idx ON external_approvers(workspace_id, created_at DESC);

CREATE TABLE IF NOT EXISTS external_approver_invites (
  invite_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  external_approver_id TEXT REFERENCES external_approvers(external_approver_id) ON DELETE SET NULL,
  external_subject TEXT,
  display_name TEXT,
  token_hash TEXT NOT NULL UNIQUE,
  created_by_user_id TEXT NOT NULL REFERENCES users(id),
  accepted_by_user_id TEXT REFERENCES users(id),
  expires_at TEXT NOT NULL,
  accepted_at TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS external_approver_invites_workspace_idx ON external_approver_invites(workspace_id, created_at DESC);

CREATE TABLE IF NOT EXISTS responses (
  response_id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  choice_id TEXT,
  message TEXT,
  answers_json TEXT,
  final BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(request_id, user_id)
);
CREATE INDEX IF NOT EXISTS responses_request_idx ON responses(request_id, created_at);

CREATE TABLE IF NOT EXISTS status_updates (
  status_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  agent_token_id TEXT REFERENCES agent_tokens(agent_token_id) ON DELETE SET NULL,
  routing_rule_id TEXT REFERENCES routing_rules(routing_rule_id) ON DELETE SET NULL,
  thread_id TEXT,
  session_id TEXT,
  session_metadata_json TEXT NOT NULL DEFAULT '{}',
  message TEXT NOT NULL,
  state TEXT NOT NULL,
  next_step TEXT,
  host TEXT,
  working_directory TEXT,
  client_name TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  content_mode TEXT NOT NULL DEFAULT 'plain',
  encrypted_payload_json TEXT,
  private_recipient_version TEXT,
  context_usage_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  is_test BOOLEAN NOT NULL DEFAULT false,
  test_label TEXT
);
CREATE INDEX IF NOT EXISTS status_updates_workspace_idx ON status_updates(workspace_id, created_at DESC);

CREATE TABLE IF NOT EXISTS status_update_recipients (
  status_id TEXT NOT NULL REFERENCES status_updates(status_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY(status_id, user_id)
);
CREATE INDEX IF NOT EXISTS status_update_recipients_user_idx ON status_update_recipients(user_id, status_id);

CREATE TABLE IF NOT EXISTS tool_activities (
  tool_activity_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  agent_token_id TEXT REFERENCES agent_tokens(agent_token_id) ON DELETE SET NULL,
  routing_rule_id TEXT REFERENCES routing_rules(routing_rule_id) ON DELETE SET NULL,
  thread_id TEXT,
  session_id TEXT NOT NULL,
  turn_id TEXT,
  tool_call_id TEXT,
  tool_name TEXT NOT NULL,
  state TEXT NOT NULL,
  outcome TEXT,
  summary TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  content_mode TEXT NOT NULL DEFAULT 'plain',
  encrypted_payload_json TEXT,
  private_recipient_version TEXT,
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS tool_activities_workspace_idx ON tool_activities(workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS tool_activities_session_idx ON tool_activities(workspace_id, session_id, created_at ASC);

CREATE TABLE IF NOT EXISTS tool_activity_recipients (
  tool_activity_id TEXT NOT NULL REFERENCES tool_activities(tool_activity_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY(tool_activity_id, user_id)
);
CREATE INDEX IF NOT EXISTS tool_activity_recipients_user_idx ON tool_activity_recipients(user_id, tool_activity_id);

CREATE TABLE IF NOT EXISTS approval_devices (
  device_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  platform TEXT,
  installation_id TEXT,
  expo_push_token TEXT,
  token_hash TEXT UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  unregistered_at TEXT
);
CREATE INDEX IF NOT EXISTS approval_devices_user_idx ON approval_devices(user_id, unregistered_at);
CREATE INDEX IF NOT EXISTS approval_devices_installation_idx ON approval_devices(user_id, installation_id);

CREATE TABLE IF NOT EXISTS approval_device_keys (
  device_key_id TEXT PRIMARY KEY,
  device_id TEXT NOT NULL REFERENCES approval_devices(device_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  algorithm TEXT NOT NULL,
  public_key TEXT NOT NULL,
  public_key_fingerprint TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  revoked_at TEXT,
  UNIQUE(device_id, algorithm, public_key_fingerprint)
);
CREATE INDEX IF NOT EXISTS approval_device_keys_user_idx ON approval_device_keys(user_id, revoked_at);
CREATE INDEX IF NOT EXISTS approval_device_keys_device_idx ON approval_device_keys(device_id, revoked_at);

CREATE TABLE IF NOT EXISTS device_pairing_codes (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  used_at TEXT
);
CREATE INDEX IF NOT EXISTS device_pairing_codes_cleanup_idx ON device_pairing_codes(expires_at, used_at);

CREATE TABLE IF NOT EXISTS event_tickets (
  token_hash TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  used_at TEXT
);
CREATE INDEX IF NOT EXISTS event_tickets_cleanup_idx ON event_tickets(expires_at, used_at);

CREATE TABLE IF NOT EXISTS request_waiters (
  waiter_id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  agent_token_id TEXT NOT NULL,
  client_run_id TEXT,
  transport TEXT NOT NULL DEFAULT 'long_poll',
  state TEXT NOT NULL DEFAULT 'waiting',
  last_seen_at TEXT NOT NULL,
  lease_expires_at TEXT NOT NULL,
  credential_expires_at TEXT NOT NULL,
  stopped_at TEXT,
  stop_reason TEXT,
  error_code TEXT,
  error_message TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS request_waiters_request_idx ON request_waiters(request_id, created_at DESC);
CREATE INDEX IF NOT EXISTS request_waiters_workspace_idx ON request_waiters(workspace_id, state, lease_expires_at);

CREATE TABLE IF NOT EXISTS request_waiter_tokens (
  token_hash TEXT PRIMARY KEY,
  waiter_id TEXT NOT NULL REFERENCES request_waiters(waiter_id) ON DELETE CASCADE,
  request_id TEXT NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  agent_token_id TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  last_used_at TEXT
);
CREATE INDEX IF NOT EXISTS request_waiter_tokens_cleanup_idx ON request_waiter_tokens(expires_at);

CREATE TABLE IF NOT EXISTS availability (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  state TEXT NOT NULL,
  last_seen_at TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(user_id, workspace_id)
);

CREATE TABLE IF NOT EXISTS mobile_diagnostics (
  diagnostic_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id TEXT,
  level TEXT NOT NULL,
  area TEXT NOT NULL,
  message TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS mobile_diagnostics_workspace_idx ON mobile_diagnostics(workspace_id, created_at DESC);

CREATE TABLE IF NOT EXISTS audit_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(workspace_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_events_workspace_idx ON audit_events(workspace_id, event_id DESC);

CREATE TABLE IF NOT EXISTS personal_entitlements (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  trial_started_at TEXT NOT NULL,
  app_unlocked_at TEXT,
  hosted_subscription_ends_at TEXT,
  hosted_subscription_canceled_at TEXT,
  hosted_data_deleted_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_products (
  id TEXT PRIMARY KEY,
  product_key TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL,
  entitlement_key TEXT NOT NULL,
  apple_product_id TEXT,
  google_product_id TEXT,
  google_base_plan_id TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_purchase_attempts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_key TEXT NOT NULL,
  product_group TEXT NOT NULL,
  platform TEXT NOT NULL,
  provider TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_user_id TEXT,
  idempotency_key TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(provider, idempotency_key)
);
CREATE INDEX IF NOT EXISTS billing_purchase_attempts_user_idx ON billing_purchase_attempts(user_id, product_group, status, expires_at);

CREATE TABLE IF NOT EXISTS billing_transactions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  environment TEXT NOT NULL,
  product_key TEXT NOT NULL,
  entitlement_key TEXT NOT NULL,
  platform TEXT NOT NULL,
  provider_transaction_id TEXT,
  provider_original_transaction_id TEXT,
  provider_purchase_token TEXT,
  status TEXT NOT NULL,
  purchased_at TEXT,
  expires_at TEXT,
  canceled_at TEXT,
  revoked_at TEXT,
  raw_event_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS billing_transactions_provider_tx_idx ON billing_transactions(provider, provider_transaction_id) WHERE provider_transaction_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS billing_transactions_provider_token_idx ON billing_transactions(provider, provider_purchase_token) WHERE provider_purchase_token IS NOT NULL;

CREATE TABLE IF NOT EXISTS billing_receipt_owners (
  provider TEXT NOT NULL,
  environment TEXT NOT NULL,
  platform TEXT NOT NULL,
  entitlement_key TEXT NOT NULL,
  receipt_key TEXT NOT NULL,
  product_key TEXT NOT NULL,
  owner_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  PRIMARY KEY(provider, environment, platform, entitlement_key, receipt_key)
);
CREATE INDEX IF NOT EXISTS billing_receipt_owners_user_idx ON billing_receipt_owners(owner_user_id, entitlement_key);

CREATE TABLE IF NOT EXISTS billing_identity_conflicts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  environment TEXT NOT NULL,
  platform TEXT NOT NULL,
  product_key TEXT NOT NULL,
  entitlement_key TEXT NOT NULL,
  receipt_key TEXT NOT NULL,
  code TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(user_id, provider, environment, platform, entitlement_key, receipt_key, code)
);
CREATE INDEX IF NOT EXISTS billing_identity_conflicts_user_idx ON billing_identity_conflicts(user_id, updated_at DESC);
`;
