import Constants from "expo-constants";
import { StyleSheet } from "react-native";

const SESSION_STACK_BOUNDARY_COLOR = "#2563eb";
const SESSION_LANE_TITLE_BAR_HEIGHT = 52;
const SESSION_TIMELINE_CONTENT_TOP_PADDING = 14;

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: "#f7f2e8",
    paddingTop: Constants.statusBarHeight,
  },
  emptyState: {
    alignItems: "stretch",
    flex: 1,
    gap: 12,
    justifyContent: "center",
    padding: 24,
  },
  title: {
    color: "#202124",
    fontSize: 28,
    fontWeight: "900",
    textAlign: "center",
  },
  subtitle: {
    color: "#6d6657",
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 21,
    marginBottom: 8,
    textAlign: "center",
  },
  input: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    color: "#202124",
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  hostedOnboarding: {
    gap: 14,
    padding: 24,
  },
  fieldGroup: {
    gap: 8,
    marginTop: 12,
  },
  label: {
    color: "#545044",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
  },
  brandButton: {
    alignSelf: "flex-start",
    minHeight: 36,
    justifyContent: "center",
  },
  brandTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  brand: {
    color: "#202124",
    fontSize: 28,
    fontWeight: "800",
  },
  brandNeedsInputBadge: {
    alignItems: "center",
    backgroundColor: "#b91c1c",
    borderColor: "#f8f5ed",
    borderRadius: 999,
    borderWidth: 2,
    height: 24,
    justifyContent: "center",
    minWidth: 24,
    paddingHorizontal: 7,
  },
  brandNeedsInputBadgeText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 15,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "#202124",
    borderRadius: 8,
    height: 46,
    justifyContent: "center",
    minWidth: 64,
    paddingHorizontal: 12,
    position: "relative",
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
  },
  stackActionButton: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderWidth: 1,
    minWidth: 52,
  },
  stackModeButton: {
    minWidth: 46,
    paddingHorizontal: 10,
  },
  stackModeButtonIcon: {
    color: "#202124",
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 26,
  },
  stackActionButtonCount: {
    color: "#7a725f",
    fontSize: 22,
    fontWeight: "900",
    left: 0,
    lineHeight: 28,
    opacity: 0.34,
    position: "absolute",
    right: 0,
    textAlign: "center",
    top: 9,
    zIndex: 0,
  },
  stackActionButtonText: {
    color: "#202124",
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 28,
    zIndex: 1,
  },
  menuIconText: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 28,
  },
  menuOverlay: {
    flex: 1,
  },
  menuBackdrop: {
    backgroundColor: "rgba(32, 33, 36, 0.38)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  menuBackdropPressable: {
    flex: 1,
  },
  sideMenu: {
    backgroundColor: "#f7f2e8",
    borderLeftColor: "#ded6c6",
    borderLeftWidth: 1,
    bottom: 0,
    maxWidth: 360,
    paddingBottom: 20,
    paddingHorizontal: 18,
    paddingTop: Constants.statusBarHeight + 18,
    position: "absolute",
    right: 0,
    top: 0,
    width: "82%",
  },
  sideMenuHeader: {
    gap: 14,
  },
  sideMenuTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sideMenuTitle: {
    color: "#202124",
    fontSize: 26,
    fontWeight: "900",
  },
  closeButton: {
    alignItems: "center",
    borderColor: "#202124",
    borderRadius: 10,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  closeButtonText: {
    color: "#202124",
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 30,
  },
  accountsSection: {
    backgroundColor: "#efe8da",
    borderColor: "#ded6c6",
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    marginTop: 18,
    padding: 10,
  },
  accountsList: {
    gap: 6,
  },
  menuSectionLabel: {
    color: "#7a725f",
    fontSize: 12,
    fontWeight: "900",
    paddingHorizontal: 4,
    textTransform: "uppercase",
  },
  accountMenuItem: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 62,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  accountMenuItemActive: {
    borderColor: "#202124",
    borderWidth: 2,
  },
  accountColorDot: {
    borderRadius: 7,
    height: 14,
    width: 14,
  },
  accountMenuTextWrap: {
    flex: 1,
  },
  accountMenuTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  accountMenuName: {
    color: "#202124",
    flex: 1,
    fontSize: 15,
    fontWeight: "900",
  },
  currentAccountPill: {
    backgroundColor: "#202124",
    borderRadius: 8,
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 2,
    textTransform: "uppercase",
  },
  accountMenuMeta: {
    color: "#6d6657",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  accountMenuStatus: {
    color: "#7a725f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  menuItems: {
    gap: 8,
    marginTop: 22,
  },
  menuItem: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  menuItemActive: {
    backgroundColor: "#202124",
    borderColor: "#202124",
  },
  menuItemIcon: {
    color: "#202124",
    fontSize: 20,
    fontWeight: "900",
    width: 26,
  },
  menuItemText: {
    color: "#202124",
    fontSize: 16,
    fontWeight: "900",
  },
  menuItemTextActive: {
    color: "#ffffff",
  },
  sideMenuFooter: {
    borderTopColor: "#ded6c6",
    borderTopWidth: 1,
    marginTop: "auto",
    paddingTop: 14,
  },
  serverLabel: {
    color: "#6d6657",
    fontSize: 12,
    fontWeight: "700",
  },
  scannerPane: {
    flex: 1,
  },
  scanner: {
    flex: 1,
  },
  scannerFooter: {
    backgroundColor: "#f7f2e8",
    padding: 20,
  },
  iconButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  waitingPane: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  waitingTitle: {
    color: "#202124",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 12,
  },
  waitingSubtitle: {
    color: "#5f6368",
    fontSize: 15,
    marginTop: 8,
    textAlign: "center",
  },
  requestsPane: {
    flex: 1,
  },
  historyPane: {
    flex: 1,
    paddingHorizontal: 20,
  },
  historyHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionHeading: {
    color: "#202124",
    fontSize: 24,
    fontWeight: "900",
  },
  smallButton: {
    alignItems: "center",
    borderColor: "#202124",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 40,
    justifyContent: "center",
    minWidth: 88,
    paddingHorizontal: 12,
  },
  smallButtonText: {
    color: "#202124",
    fontSize: 14,
    fontWeight: "900",
  },
  historyList: {
    gap: 10,
    paddingBottom: 22,
  },
  historyDetailContent: {
    paddingBottom: 24,
  },
  historyDetailType: {
    color: "#6d6657",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  historyDetailNav: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  historyNavButton: {
    alignItems: "center",
    backgroundColor: "#202124",
    borderRadius: 8,
    flex: 1,
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  historyNavButtonDisabled: {
    backgroundColor: "#e3dbc9",
  },
  historyNavButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
  historyNavButtonTextDisabled: {
    color: "#8e8778",
  },
  historyRow: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  historyRowTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  historyTitle: {
    color: "#202124",
    flex: 1,
    fontSize: 16,
    fontWeight: "900",
  },
  historyStatus: {
    color: "#5f5a4f",
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  historyStatusApprove: {
    color: "#1f6f5b",
  },
  historyStatusDeny: {
    color: "#a33b2f",
  },
  historyMeta: {
    color: "#6d6657",
    fontSize: 13,
    fontWeight: "700",
  },
  historyCommandPanel: {
    backgroundColor: "#f7f1e4",
    borderColor: "#e3dbc9",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  historyCommandRow: {
    gap: 3,
  },
  historyCommandLabel: {
    color: "#6d6657",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  historyCommandValue: {
    color: "#202124",
    fontFamily: "monospace",
    fontSize: 13,
    lineHeight: 19,
  },
  historyResponses: {
    borderTopColor: "#e3dbc9",
    borderTopWidth: 1,
    gap: 4,
    marginTop: 4,
    paddingTop: 8,
  },
  historyResponseText: {
    color: "#5f5a4f",
    fontSize: 12,
    fontWeight: "800",
  },
  emptyText: {
    color: "#6d6657",
    paddingVertical: 16,
    textAlign: "center",
  },
  requestStrip: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  requestPill: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    maxWidth: 160,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  requestPillActive: {
    borderColor: "#1f6f5b",
  },
  requestPillText: {
    color: "#202124",
    fontSize: 13,
    fontWeight: "800",
  },
  requestScroll: {
    flex: 1,
  },
  requestContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  sessionStackViewport: {
    flex: 1,
    position: "relative",
  },
  sessionStackContent: {
    gap: 0,
  },
  pendingLaneNudge: {
    alignItems: "center",
    backgroundColor: "#0f6b57",
    borderColor: "#f8f5ed",
    borderRadius: 999,
    borderWidth: 2,
    height: 34,
    justifyContent: "center",
    minWidth: 50,
    paddingHorizontal: 12,
    position: "absolute",
    right: 14,
    zIndex: 5,
  },
  pendingLaneNudgeBottom: {
    bottom: 14,
  },
  pendingLaneNudgeTop: {
    top: 14,
  },
  pendingLaneNudgeText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
    lineHeight: 18,
  },
  sessionExpansionRoot: {
    flex: 1,
    overflow: "hidden",
  },
  sessionStackUnderlay: {
    ...StyleSheet.absoluteFillObject,
  },
  sessionStackUnderlayHidden: {
    opacity: 0,
  },
  sessionExpansionOverlay: {
    backgroundColor: "#f8f5ed",
    borderColor: "#64756d",
    borderWidth: 2,
    overflow: "hidden",
    position: "absolute",
    zIndex: 12,
  },
  sessionLane: {
    borderRadius: 0,
  },
  sessionLaneReorderPreview: {
    shadowColor: SESSION_STACK_BOUNDARY_COLOR,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    zIndex: 3,
  },
  sessionLaneHidden: {
    opacity: 0,
  },
  sessionLaneFrame: {
    backgroundColor: "#ffffff",
    borderColor: "#64756d",
    borderRadius: 0,
    borderWidth: 2,
    flex: 1,
    overflow: "hidden",
  },
  sessionLaneFrameExpanded: {
    backgroundColor: "#f8f5ed",
    borderRadius: 0,
    borderWidth: 0,
  },
  sessionLaneTitleBar: {
    alignItems: "center",
    backgroundColor: "#e8f2ed",
    borderBottomColor: "#64756d",
    borderBottomWidth: 2,
    flexDirection: "row",
    height: SESSION_LANE_TITLE_BAR_HEIGHT,
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 0,
    zIndex: 1,
  },
  sessionLaneTitleBarExpanded: {
    borderBottomColor: "#64756d",
    borderBottomWidth: 2,
  },
  sessionLaneTitleCluster: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    minWidth: 0,
  },
  sessionStackBackButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#64756d",
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    marginRight: 10,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  sessionStackBackButtonText: {
    color: "#202124",
    fontSize: 14,
    fontWeight: "900",
  },
  sessionLaneTitleText: {
    color: "#202124",
    flex: 1,
    fontSize: 16,
    fontWeight: "900",
  },
  sessionLaneViewport: {
    backgroundColor: "#f8f5ed",
    flex: 1,
    overflow: "hidden",
  },
  sessionLaneOverviewScroll: {
    flex: 1,
  },
  sessionLaneOverviewScrollPreparing: {
    opacity: 0,
  },
  sessionLaneTimelineClipContent: {
    paddingHorizontal: 20,
    paddingTop: SESSION_TIMELINE_CONTENT_TOP_PADDING,
    paddingBottom: 34,
  },
  sessionLaneTimelineClipContentFill: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sessionLaneSkeletonCard: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
    marginHorizontal: 20,
    marginTop: 14,
    padding: 14,
  },
  sessionLaneSkeletonHeader: {
    backgroundColor: "#edf7f3",
    borderRadius: 999,
    height: 18,
    width: 118,
  },
  sessionLaneSkeletonLineWide: {
    backgroundColor: "#e3dbc9",
    borderRadius: 999,
    height: 24,
    width: "84%",
  },
  sessionLaneSkeletonLine: {
    backgroundColor: "#eee8dc",
    borderRadius: 999,
    height: 16,
    width: "58%",
  },
  sessionLaneSkeletonText: {
    color: "#8e8778",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 10,
    textAlign: "center",
  },
  statusStateNeedsInput: {
    color: "#b42318",
  },
  statusStateWaiting: {
    color: "#6b7280",
  },
  statusStateActive: {
    color: "#2563eb",
  },
  statusStateBlocked: {
    color: "#b45309",
  },
  statusStateFailed: {
    color: "#7f1d1d",
  },
  statusStateComplete: {
    color: "#1f6f5b",
  },
  statusStateRecent: {
    color: "#475569",
  },
  archiveSessionButton: {
    alignSelf: "flex-start",
    marginHorizontal: 20,
    marginTop: 8,
  },
  archiveSessionButtonEmbedded: {
    alignSelf: "flex-start",
    marginTop: 10,
  },
  nonInteractiveControl: {
    backgroundColor: "#e8f0fe",
    borderRadius: 8,
    color: "#174ea6",
    fontSize: 13,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  sessionTimelinePane: {
    backgroundColor: "#f8f5ed",
  },
  sessionTimelineScroll: {
    backgroundColor: "#f8f5ed",
  },
  sessionTimelineContent: {
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: SESSION_TIMELINE_CONTENT_TOP_PADDING,
    paddingBottom: 34,
  },
  sessionTimelineItems: {
    gap: 14,
  },
  sessionTimelineHeader: {
    gap: 6,
    marginBottom: 2,
  },
  sessionTimelineItem: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  sessionTimelineItemFocused: {
    borderColor: "#1f6f5b",
    borderWidth: 2,
  },
  pastRequestCollapsed: {
    gap: 8,
    paddingVertical: 12,
  },
  pastRequestCollapsedHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  pastRequestCollapsedTitle: {
    color: "#202124",
    flex: 1,
    fontSize: 17,
    fontWeight: "900",
    lineHeight: 22,
  },
  pastRequestAnswer: {
    color: "#1f6f5b",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 20,
  },
  pastRequestExpanded: {
    borderColor: "#cfc6b4",
  },
  pastRequestCollapseButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    flexDirection: "row",
    gap: 4,
  },
  pastRequestOptionsPanel: {
    backgroundColor: "#f8f5ed",
    borderColor: "#e3dbc9",
    borderRadius: 10,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  pastRequestOptionRow: {
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  pastRequestOptionSelected: {
    backgroundColor: "#edf7f3",
    borderColor: "#1f6f5b",
  },
  pastRequestOptionText: {
    color: "#5f5a4f",
    fontSize: 14,
    fontWeight: "800",
  },
  pastRequestOptionTextSelected: {
    color: "#1f6f5b",
    fontWeight: "900",
  },
  newActivityNudge: {
    alignItems: "center",
    backgroundColor: "#202124",
    borderRadius: 999,
    bottom: 26,
    height: 46,
    justifyContent: "center",
    position: "absolute",
    right: 18,
    width: 46,
    zIndex: 4,
  },
  newActivityNudgeText: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 30,
  },
  testRequestBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#fef3c7",
    borderColor: "#d8c391",
    borderRadius: 999,
    borderWidth: 1,
    color: "#6d4d12",
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: "uppercase",
  },
  warningText: {
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
    borderRadius: 8,
    borderWidth: 1,
    color: "#9a3412",
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
    padding: 10,
  },
  focusRequestButton: {
    alignSelf: "flex-start",
    marginTop: 4,
  },
  loadEarlierSessionHistoryButton: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  statusCard: {
    backgroundColor: "#edf7f3",
    borderColor: "#b8dacd",
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
    marginBottom: 16,
    padding: 12,
  },
  statusTimelineGroup: {
    backgroundColor: "#edf7f3",
    borderColor: "#b8dacd",
    borderRadius: 12,
    borderWidth: 1,
    overflow: "hidden",
  },
  statusTimelineGroupLabel: {
    color: "#184f42",
    fontSize: 12,
    fontWeight: "900",
    paddingHorizontal: 12,
    paddingTop: 12,
    textTransform: "uppercase",
  },
  statusTimelineRow: {
    borderTopColor: "#cfe5dc",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 12,
  },
  statusTimelineRowFirst: {
    borderTopWidth: 0,
  },
  statusTimelineTime: {
    color: "#202124",
    fontSize: 14,
    fontWeight: "900",
    minWidth: 44,
  },
  statusTimelineBody: {
    flex: 1,
    gap: 4,
  },
  statusTimelineMessage: {
    color: "#202124",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
  },
  statusTimelineState: {
    color: "#1f6f5b",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  sessionActionsPanel: {
    backgroundColor: "#fffaf0",
    borderColor: "#d8c391",
    borderRadius: 12,
    borderWidth: 1,
    gap: 4,
    marginTop: 8,
    padding: 14,
  },
  statusCardCompact: {
    marginTop: 18,
    maxWidth: 360,
    width: "100%",
  },
  statusCardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  statusLabel: {
    color: "#184f42",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  statusHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  sessionLaneSizeButton: {
    alignItems: "center",
    borderColor: "#64756d",
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  sessionLaneSizeButtonText: {
    color: "#202124",
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 20,
  },
  statusDismiss: {
    color: "#6d6657",
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 24,
  },
  statusState: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  statusMessage: {
    color: "#202124",
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  statusNext: {
    color: "#375f52",
    fontSize: 14,
    fontWeight: "700",
  },
  statusMeta: {
    color: "#5f5a4f",
    fontSize: 12,
    fontWeight: "700",
  },
  detailTitle: {
    color: "#202124",
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 36,
  },
  detailTitleCompact: {
    fontSize: 24,
    lineHeight: 30,
  },
  detailTitleDense: {
    fontSize: 21,
    lineHeight: 27,
  },
  detailMeta: {
    color: "#6d6657",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 8,
  },
  responsibilityBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#edf7f3",
    borderColor: "#1f6f5b",
    borderRadius: 999,
    borderWidth: 1,
    color: "#184f42",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 12,
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  detailFacts: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  riskBadge: {
    borderRadius: 8,
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    textTransform: "uppercase",
  },
  riskHigh: {
    backgroundColor: "#a33b2f",
  },
  riskMedium: {
    backgroundColor: "#8a681f",
  },
  riskLow: {
    backgroundColor: "#1f6f5b",
  },
  factText: {
    color: "#5f5a4f",
    fontSize: 14,
    fontWeight: "800",
  },
  cwdText: {
    color: "#6d6657",
    fontFamily: "monospace",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 12,
  },
  bodyText: {
    color: "#202124",
    fontSize: 17,
    lineHeight: 25,
    marginTop: 22,
  },
  markdownBody: {
    marginTop: 22,
  },
  commandText: {
    backgroundColor: "#202124",
    borderRadius: 8,
    color: "#f8f5ed",
    fontFamily: "monospace",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 18,
    padding: 14,
  },
  contextSummaryPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 16,
    padding: 12,
  },
  contextSummaryPanelDocked: {
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRadius: 0,
    borderRightWidth: 0,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  contextSummaryPanelExpanded: {
    maxHeight: "44%",
  },
  contextSummaryHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  contextSummaryTitle: {
    color: "#545044",
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  contextSummaryChevron: {
    color: "#545044",
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 20,
  },
  contextSummaryRows: {
    gap: 8,
  },
  contextSummaryRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  contextSummaryLabel: {
    color: "#6d6657",
    fontSize: 13,
    fontWeight: "900",
    minWidth: 78,
  },
  contextSummaryValue: {
    color: "#202124",
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    textAlign: "right",
  },
  contextSummaryText: {
    color: "#4b463b",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
  },
  contextSummaryTextDocked: {
    flex: 1,
    fontWeight: "800",
  },
  responsePanel: {
    backgroundColor: "#fffaf0",
    borderColor: "#d8c391",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 14,
    padding: 12,
  },
  responseTitle: {
    color: "#5f4724",
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  responseMessage: {
    color: "#202124",
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  responseMeta: {
    color: "#6d6657",
    fontSize: 13,
    fontWeight: "800",
  },
  responseList: {
    gap: 6,
    marginTop: 2,
  },
  responseRow: {
    backgroundColor: "#ffffff",
    borderRadius: 6,
    padding: 8,
  },
  responseText: {
    color: "#202124",
    fontSize: 13,
    fontWeight: "800",
  },
  responseEntryMessage: {
    color: "#6d6657",
    fontSize: 13,
    marginTop: 3,
  },
  contextPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 18,
    padding: 12,
  },
  contextTitle: {
    color: "#545044",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 8,
  },
  contextText: {
    color: "#202124",
    fontFamily: "monospace",
    fontSize: 13,
    lineHeight: 19,
  },
  questionnairePanel: {
    gap: 14,
    marginTop: 18,
  },
  questionCard: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  questionHeader: {
    color: "#6d6657",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  questionText: {
    color: "#202124",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 24,
  },
  questionHint: {
    color: "#5f5a4f",
    fontSize: 13,
    fontWeight: "700",
  },
  historyAnswerText: {
    color: "#184f42",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
  },
  questionOptions: {
    gap: 8,
  },
  optionButton: {
    alignItems: "center",
    backgroundColor: "#f8f5ed",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  optionButtonActive: {
    backgroundColor: "#edf7f3",
    borderColor: "#1f6f5b",
  },
  optionMarker: {
    alignItems: "center",
    borderColor: "#8e8778",
    borderRadius: 999,
    borderWidth: 2,
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  optionMarkerMulti: {
    borderRadius: 5,
  },
  optionMarkerActive: {
    borderColor: "#1f6f5b",
  },
  optionMarkerDot: {
    backgroundColor: "#1f6f5b",
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  optionFavoriteIcon: {
    color: "#fbbc04",
    fontSize: 20,
    fontWeight: "900",
  },
  optionLabelStack: {
    flex: 1,
    gap: 3,
  },
  optionLabel: {
    color: "#202124",
    fontSize: 16,
    fontWeight: "700",
  },
  optionLabelActive: {
    color: "#184f42",
  },
  optionDescription: {
    color: "#64748b",
    fontSize: 13,
    lineHeight: 18,
  },
  reply: {
    backgroundColor: "#ffffff",
    borderColor: "#ded6c6",
    borderRadius: 8,
    borderWidth: 1,
    color: "#202124",
    fontSize: 16,
    marginTop: 18,
    minHeight: 92,
    padding: 12,
    textAlignVertical: "top",
  },
  actions: {
    backgroundColor: "#f7f2e8",
    borderTopColor: "#e3dbc9",
    borderTopWidth: 1,
    gap: 10,
    padding: 20,
  },
  actionsInline: {
    marginTop: "auto",
  },
  choiceButton: {
    alignItems: "center",
    backgroundColor: "#3c4043",
    borderRadius: 8,
    minHeight: 52,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  approveButton: {
    backgroundColor: "#1f6f5b",
  },
  denyButton: {
    backgroundColor: "#a33b2f",
  },
  submitButton: {
    backgroundColor: "#202124",
  },
  flaggedChoiceButton: {
    borderColor: "#fbbc04",
    borderWidth: 2,
  },
  choiceButtonDisabled: {
    backgroundColor: "#8e8778",
  },
  readOnlyPanel: {
    backgroundColor: "#fff6d8",
    borderColor: "#e5c66a",
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  actionHint: {
    color: "#5f5a4f",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
    textAlign: "center",
  },
  choiceContent: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 34,
    position: "relative",
    width: "100%",
  },
  choiceFavoriteIcon: {
    color: "#fbbc04",
    fontSize: 22,
    fontWeight: "900",
    left: 0,
    position: "absolute",
  },
  choiceLabelStack: {
    alignItems: "center",
    gap: 4,
    width: "100%",
  },
  choiceText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
  },
  choiceDescription: {
    color: "rgba(255, 255, 255, 0.82)",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    textAlign: "center",
  },
  choiceBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    justifyContent: "center",
  },
  choiceBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    borderRadius: 999,
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 2,
    textTransform: "uppercase",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#202124",
    borderRadius: 8,
    minHeight: 52,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#202124",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 20,
    minHeight: 46,
    justifyContent: "center",
    minWidth: 120,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: "#202124",
    fontSize: 15,
    fontWeight: "900",
  },
  errorText: {
    color: "#9b1c1c",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    textAlign: "center",
  },
});
